openapi: 3.0.3
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /people:
    $ref: "paths/person.yml#/~1people"
  /people/{lname}:
    $ref: "paths/person.yml#/~1people~1{lname}"
  /notes:
    $ref: "paths/note.yml#/~1notes"
  /notes/{note_id}:
    $ref: "paths/note.yml#/~1notes~1{note_id}"